import { Registry } from "@/registry/schema";

export const examples: Registry = [
  {
    name: "fadedowndemo",
    type: "registry:example",
    registryDependencies: ["fadedown"],
    files: ["demos/fadedown-demo.tsx"],
  },
  {
    name: "dynamicsquaredemo",
    type: "registry:example",
    files: ["demos/dynamicsquare-demo.tsx"],
  },
  {
    name: "testimonalcarouseldemo",
    type: "registry:example",
    registryDependencies: ["carousel"],
    files: ["demos/testimonal-carousel.tsx"],
  },
  {
    name: "hackerbgdemo",
    type: "registry:example",
    files: ["demos/hackerbg-demo.tsx"],
  },
  {
    name: "featuresdemo",
    type: "registry:example",
    registryDependencies: ["features"],
    files: ["demos/features-demo.tsx"],
  },
  {
    name: "integrationsdemo",
    type: "registry:example",
    registryDependencies: ["integrations"],
    files: ["demos/integrations-demo.tsx"],
  },
  {
    name: "logomarqueedemo",
    type: "registry:example",
    files: ["demos/logomarquee.tsx"],
  },
  {
    name: "codesnippetdemo",
    type: "registry:example",
    registryDependencies: ["codesnippet"],
    files: ["demos/codesnippet-demo.tsx"],
  },
  {
    name: "staticstepperdemo",
    type: "registry:example",
    files: ["demos/staticstepper-demo.tsx"],
  },
  {
    name: "featurefourdemo",
    type: "registry:example",
    files: ["demos/featurefour-demo.tsx"],
  },
  {
    name: "animatedcarddemo",
    type: "registry:example",
    registryDependencies: ["animatedcard"],
    files: ["demos/animatedcard-demo.tsx"],
  },
  {
    name: "signaturedemo",
    type: "registry:example",
    registryDependencies: ["signature"],
    files: ["demos/signature-demo.tsx"],
  },
  {
    name: "gradientpricingdemo",
    type: "registry:example",
    files: ["demos/gradientpricing-demo.tsx"],
  },
  {
    name: "scrollprogressdemo",
    type: "registry:example",
    registryDependencies: ["scrollprogress"],
    files: ["demos/scrollprogress-demo.tsx"],
  },
  {
    name: "cardcommentdemo",
    type: "registry:example",
    files: ["demos/cardcomment-demo.tsx"],
  },
  {
    name: "scalesliderdemo",
    type: "registry:example",
    registryDependencies: ["scaleslider"],
    files: ["demos/scaleslider-demo.tsx"],
  },
  {
    name: "scratchtorevealdemo",
    type: "registry:example",
    registryDependencies: ["scratchtoreveal"],
    files: ["demos/scratchtoreveal-demo.tsx"],
  },
  {
    name: "warpcontainerdemo",
    type: "registry:example",
    registryDependencies: ["warpcontainer"],
    files: ["demos/warpanimation-demo.tsx"],
  },
  {
    name: "tweetgriddemo",
    type: "registry:example",
    registryDependencies: ["tweetgrid"],
    files: ["demos/tweetgrid-demo.tsx"],
  },
  {
    name: "fadeindemo",
    type: "registry:example",
    registryDependencies: ["fadein"],
    files: ["demos/fadein-demo.tsx"],
  },
  {
    name: "fadeupdemo",
    type: "registry:example",
    registryDependencies: ["fadeup"],
    files: ["demos/fadeup-demo.tsx"],
  },
  {
    name: "gradualspacingdemo",
    type: "registry:example",
    registryDependencies: ["gradualspacing"],
    files: ["demos/gradualspacing-demo.tsx"],
  },
  {
    name: "letterpullupdemo",
    type: "registry:example",
    registryDependencies: ["letterpullup"],
    files: ["demos/letterpullup-demo.tsx"],
  },
  {
    name: "multidirectionalslidedemo",
    type: "registry:example",
    registryDependencies: ["multidirectionalslide"],
    files: ["demos/multidirectionalslide-demo.tsx"],
  },
  {
    name: "scrollbasedvelocitydemo",
    type: "registry:example",
    registryDependencies: ["scrollbasedvelocity"],
    files: ["demos/scrollbasedvelocity-demo.tsx"],
  },
  {
    name: "seperateawaydemo",
    type: "registry:example",
    registryDependencies: ["seperateaway"],
    files: ["demos/seperateaway-demo.tsx"],
  },
  {
    name: "wavytextdemo",
    type: "registry:example",
    registryDependencies: ["wavytext"],
    files: ["demos/wavytext-demo.tsx"],
  },
  {
    name: "morphingtextdemo",
    type: "registry:example",
    files: ["demos/morphingtext-demo.tsx"],
  },
  {
    name: "blurindemo",
    type: "registry:example",
    registryDependencies: ["blurin"],
    files: ["demos/blurin-demo.tsx"],
  },
  {
    name: "wordpullupdemo",
    type: "registry:example",
    registryDependencies: ["wordpullup"],
    files: ["demos/wordpullup-demo.tsx"],
  },
  {
    name: "bentodemo",
    type: "registry:example",
    registryDependencies: ["bentocard"],
    files: ["demos/bento-demo.tsx"],
  },
  {
    name: "headerdemo",
    type: "registry:example",
    registryDependencies: ["header"],
    files: ["demos/header-demo.tsx"],
  },
  {
    name: "novatrixdemo",
    type: "registry:example",
    registryDependencies: ["novatrix"],
    files: ["demos/novatrixbg-demo.tsx"],
  },
  {
    name: "testimonalsliderdemo",
    type: "registry:example",
    registryDependencies: ["testimonalslider"],
    files: ["demos/testimonalslider-demo.tsx"],
  },
  {
    name: "cobeglobedemo",
    type: "registry:example",
    registryDependencies: ["cobeglobe"],
    files: ["demos/cobeglobe-demo.tsx"],
  },
  {
    name: "cobedraggabledemo",
    type: "registry:example",
    registryDependencies: ["cobedraggable"],
    files: ["demos/cobedraggable-demo.tsx"],
  },
  {
    name: "cobeautodraggabledemo",
    type: "registry:example",
    registryDependencies: ["cobeautodraggable"],
    files: ["demos/cobeautodraggable-demo.tsx"],
  },
  {
    name: "coberotatetolocationdemo",
    type: "registry:example",
    registryDependencies: ["coberotatetolocation"],
    files: ["demos/coberotatetolocation-demo.tsx"],
  },
  {
    name: "cobescaleddemo",
    type: "registry:example",
    registryDependencies: ["cobescaled"],
    files: ["demos/cobescaled-demo.tsx"],
  },
  {
    name: "testimonalsdemo",
    type: "registry:example",
    registryDependencies: ["testimonals"],
    files: ["demos/testimonals-demo.tsx"],
  },
  {
    name: "hovermedemo",
    type: "registry:example",
    files: ["demos/hoverme-demo.tsx"],
  },
  {
    name: "gitstardemo",
    type: "registry:example",
    files: ["demos/gitstar-demo.tsx"],
  },
  {
    name: "logoclouddemo",
    type: "registry:example",
    files: ["demos/logocloud-demo.tsx"],
  },
  {
    name: "interactivebuttondemo",
    type: "registry:example",
    registryDependencies: ["interactivebutton"],
    files: ["demos/interactivebutton-demo.tsx"],
  },
  {
    name: "pricingdemo",
    type: "registry:example",
    files: ["demos/pricing-demo.tsx"],
  },
  {
    name: "shimmerdemo",
    type: "registry:example",
    files: ["demos/shimmerbutton-demo.tsx"],
  },
  {
    name: "colorchangingdemo",
    type: "registry:example",
    files: ["demos/colorchanging-demo.tsx"],
  },
  {
    name: "spotlightdemo",
    type: "registry:example",
    files: ["demos/spotlight-demo.tsx"],
  },
  {
    name: "borderdemo",
    type: "registry:example",
    files: ["demos/borderbutton-demo.tsx"],
  },
];
