blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/karthikmudunuri/eldoraui/discussions/new?category=general
    about: For usage questions, please usee GitHub Discussions instead of posting an issue. 
