/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "safari-browser": {
    name: "safari-browser",
    description: "A safari browser component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/safari-browser.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/safari-browser.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "macbook-pro": {
    name: "macbook-pro",
    description: "A MacBook Pro SVG component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/macbook-pro.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/macbook-pro.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "iphone-17-pro": {
    name: "iphone-17-pro",
    description: "An iPhone 17 Pro SVG component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/iphone-17-pro.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/iphone-17-pro.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "ipad": {
    name: "ipad",
    description: "An iPad SVG component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/ipad.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/ipad.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "browser": {
    name: "browser",
    description: "A browser SVG component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/browser.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/browser.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe": {
    name: "cobe-globe",
    description: "A cobe globe component.",
    type: "registry:ui",
    registryDependencies: ["button","utils"],
    files: [{
      path: "registry/eldoraui/cobe-globe.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/cobe-globe.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "github-inline-comments": {
    name: "github-inline-comments",
    description: "A github inline comments component.",
    type: "registry:ui",
    registryDependencies: ["button","utils","tooltip","badge","textarea","separator","avatar"],
    files: [{
      path: "registry/eldoraui/github-inline-comments.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/github-inline-comments.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-badge": {
    name: "animated-badge",
    description: "An animated badge component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/animated-badge.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/animated-badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid": {
    name: "grid",
    description: "A grid component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/eldoraui/grid.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/grid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "clerk-otp": {
    name: "clerk-otp",
    description: "A clerk OTP component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/eldoraui/clerk-otp.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/clerk-otp.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "marquee": {
    name: "marquee",
    description: "A performant, customizable marquee (scrolling text/content) component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/eldoraui/marquee.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/marquee.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "integrations": {
    name: "integrations",
    description: "An integrations component.",
    type: "registry:ui",
    registryDependencies: ["utils","marquee"],
    files: [{
      path: "registry/eldoraui/integrations.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/integrations.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "terminal": {
    name: "terminal",
    description: "A terminal component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/terminal.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/terminal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "safari-browser-demo": {
    name: "safari-browser-demo",
    description: "Example showing a safari-browser-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/safari-browser"],
    files: [{
      path: "registry/example/safari-browser-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/safari-browser-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "macbook-pro-demo": {
    name: "macbook-pro-demo",
    description: "Example showing a macbook-pro-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/macbook-pro"],
    files: [{
      path: "registry/example/macbook-pro-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/macbook-pro-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "iphone-17-pro-demo": {
    name: "iphone-17-pro-demo",
    description: "Example showing a iphone-17-pro-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/iphone-17-pro"],
    files: [{
      path: "registry/example/iphone-17-pro-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/iphone-17-pro-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "ipad-demo": {
    name: "ipad-demo",
    description: "Example showing a ipad-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/ipad"],
    files: [{
      path: "registry/example/ipad-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/ipad-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "browser-demo": {
    name: "browser-demo",
    description: "Example showing a browser-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/browser"],
    files: [{
      path: "registry/example/browser-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/browser-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "browser-demo-2": {
    name: "browser-demo-2",
    description: "Example showing a browser-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/browser"],
    files: [{
      path: "registry/example/browser-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/browser-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo": {
    name: "cobe-globe-demo",
    description: "Example showing a cobe-globe-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    files: [{
      path: "registry/example/cobe-globe-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo-2": {
    name: "cobe-globe-demo-2",
    description: "Example showing a cobe-globe-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    files: [{
      path: "registry/example/cobe-globe-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo-3": {
    name: "cobe-globe-demo-3",
    description: "Example showing a cobe-globe-demo-3 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    files: [{
      path: "registry/example/cobe-globe-demo-3.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo-3.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo-4": {
    name: "cobe-globe-demo-4",
    description: "Example showing a cobe-globe-demo-4 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    files: [{
      path: "registry/example/cobe-globe-demo-4.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo-4.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo-5": {
    name: "cobe-globe-demo-5",
    description: "Example showing a cobe-globe-demo-5 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    files: [{
      path: "registry/example/cobe-globe-demo-5.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo-5.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "github-inline-comments-demo": {
    name: "github-inline-comments-demo",
    description: "Example showing a github-inline-comments-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/github-inline-comments"],
    files: [{
      path: "registry/example/github-inline-comments-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/github-inline-comments-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-badge-demo": {
    name: "animated-badge-demo",
    description: "Example showing a animated-badge-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/animated-badge"],
    files: [{
      path: "registry/example/animated-badge-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/animated-badge-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo": {
    name: "grid-demo",
    description: "Example showing a grid-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    files: [{
      path: "registry/example/grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo-2": {
    name: "grid-demo-2",
    description: "Example showing a grid-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    files: [{
      path: "registry/example/grid-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo-3": {
    name: "grid-demo-3",
    description: "Example showing a grid-demo-3 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    files: [{
      path: "registry/example/grid-demo-3.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo-3.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo-4": {
    name: "grid-demo-4",
    description: "Example showing a grid-demo-4 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    files: [{
      path: "registry/example/grid-demo-4.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo-4.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo-5": {
    name: "grid-demo-5",
    description: "Example showing a grid-demo-5 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    files: [{
      path: "registry/example/grid-demo-5.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo-5.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "clerk-otp-demo": {
    name: "clerk-otp-demo",
    description: "Example showing a clerk-otp-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/clerk-otp"],
    files: [{
      path: "registry/example/clerk-otp-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/clerk-otp-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "clerk-otp-demo-2": {
    name: "clerk-otp-demo-2",
    description: "Example showing a clerk-otp-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/clerk-otp"],
    files: [{
      path: "registry/example/clerk-otp-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/clerk-otp-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "integrations-demo": {
    name: "integrations-demo",
    description: "Example showing a integrations-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/integrations"],
    files: [{
      path: "registry/example/integrations-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/integrations-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "integrations-demo-2": {
    name: "integrations-demo-2",
    description: "Example showing a integrations-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/integrations"],
    files: [{
      path: "registry/example/integrations-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/integrations-demo-2.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "terminal-demo": {
    name: "terminal-demo",
    description: "Example showing a terminal-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/terminal"],
    files: [{
      path: "registry/example/terminal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/terminal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }