/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "safari-browser": {
    name: "safari-browser",
    description: "A safari browser component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/safari-browser.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/safari-browser.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "safari-browser"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "macbook-pro": {
    name: "macbook-pro",
    description: "A MacBook Pro SVG component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/macbook-pro.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/macbook-pro.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "macbook-pro"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "iphone-17-pro": {
    name: "iphone-17-pro",
    description: "An iPhone 17 Pro SVG component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/iphone-17-pro.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/iphone-17-pro.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "iphone-17-pro"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "ipad": {
    name: "ipad",
    description: "An iPad SVG component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/ipad.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/ipad.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "ipad"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "browser": {
    name: "browser",
    description: "A browser SVG component.",
    type: "registry:ui",
    registryDependencies: ["utils","button","badge","card","separator","input"],
    categories: [],
    files: [{
      path: "registry/eldoraui/browser.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/browser.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "browser"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe": {
    name: "cobe-globe",
    description: "A cobe globe component.",
    type: "registry:ui",
    registryDependencies: ["button","utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/cobe-globe.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/cobe-globe.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "cobe-globe"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "github-inline-comments": {
    name: "github-inline-comments",
    description: "A github inline comments component.",
    type: "registry:ui",
    registryDependencies: ["button","utils","tooltip","badge","textarea","separator","avatar"],
    categories: [],
    files: [{
      path: "registry/eldoraui/github-inline-comments.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/github-inline-comments.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "github-inline-comments"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-badge": {
    name: "animated-badge",
    description: "An animated badge component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/animated-badge.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/animated-badge.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-badge"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid": {
    name: "grid",
    description: "A grid component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/grid.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/grid.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "grid"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "clerk-otp": {
    name: "clerk-otp",
    description: "A clerk OTP component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/clerk-otp.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/clerk-otp.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "clerk-otp"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "marquee": {
    name: "marquee",
    description: "A performant, customizable marquee (scrolling text/content) component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/marquee.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/marquee.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "marquee"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "integrations": {
    name: "integrations",
    description: "An integrations component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/integrations.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/integrations.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "integrations"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "terminal": {
    name: "terminal",
    description: "A terminal component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/terminal.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/terminal.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "terminal"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonal-slider": {
    name: "testimonal-slider",
    description: "A testimonial slider component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/testimonal-slider.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/testimonal-slider.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "testimonal-slider"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "map": {
    name: "map",
    description: "An animated map component with location markers.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/map.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/map.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "map"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "svg-ripple-effect": {
    name: "svg-ripple-effect",
    description: "An SVG ripple effect component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/svg-ripple-effect.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/svg-ripple-effect.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "svg-ripple-effect"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-frameworks": {
    name: "animated-frameworks",
    description: "An animated frameworks component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/animated-frameworks.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/animated-frameworks.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-frameworks"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "blur-in-text": {
    name: "blur-in-text",
    description: "A blur in text component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/blur-in-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/blur-in-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "blur-in-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fade-text": {
    name: "fade-text",
    description: "A combined fade text component with support for in, up, and down directions.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/fade-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/fade-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "fade-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "gradual-spacing-text": {
    name: "gradual-spacing-text",
    description: "A gradual spacing text component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/gradual-spacing-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/gradual-spacing-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "gradual-spacing-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "letter-pull-up-text": {
    name: "letter-pull-up-text",
    description: "A letter pull up text component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/letter-pull-up-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/letter-pull-up-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "letter-pull-up-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "multi-direction-slide-text": {
    name: "multi-direction-slide-text",
    description: "A multi direction slide text component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/multi-direction-slide-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/multi-direction-slide-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "multi-direction-slide-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "seperate-away-text": {
    name: "seperate-away-text",
    description: "A seperate away text component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/seperate-away-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/seperate-away-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "seperate-away-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "wavy-text": {
    name: "wavy-text",
    description: "A wavy text component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/wavy-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/wavy-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "wavy-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "word-pull-up-text": {
    name: "word-pull-up-text",
    description: "A word pull up text component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/word-pull-up-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/word-pull-up-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "word-pull-up-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "novatrix-background": {
    name: "novatrix-background",
    description: "A novatrix background component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/novatrix-background.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/novatrix-background.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "novatrix-background"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "photon-beam": {
    name: "photon-beam",
    description: "A photon beam background component with animated light trails.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/photon-beam.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/photon-beam.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "photon-beam"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hacker-background": {
    name: "hacker-background",
    description: "A hacker background component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/hacker-background.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/hacker-background.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "hacker-background"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "card-flip-hover": {
    name: "card-flip-hover",
    description: "A card flip hover component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/card-flip-hover.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/card-flip-hover.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "card-flip-hover"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scale-letter-text": {
    name: "scale-letter-text",
    description: "A scale letter text component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/scale-letter-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/scale-letter-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "scale-letter-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "font-weight-text": {
    name: "font-weight-text",
    description: "A font weight text component.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/font-weight-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/font-weight-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "font-weight-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-grid-pattern": {
    name: "animated-grid-pattern",
    description: "An animated grid pattern component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/animated-grid-pattern.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/animated-grid-pattern.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-grid-pattern"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "live-button": {
    name: "live-button",
    description: "A live button component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/live-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/live-button.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "live-button"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-shiny-button": {
    name: "animated-shiny-button",
    description: "An animated shiny button component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/animated-shiny-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/animated-shiny-button.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-shiny-button"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-list": {
    name: "animated-list",
    description: "An animated list component.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/animated-list.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/animated-list.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-list"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "orbit-rotation": {
    name: "orbit-rotation",
    description: "An orbit rotation component with customizable icons.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/orbit-rotation.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/orbit-rotation.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "orbit-rotation"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logo-timeline": {
    name: "logo-timeline",
    description: "An animated logo timeline component with horizontal scrolling logos.",
    type: "registry:ui",
    registryDependencies: ["utils"],
    categories: [],
    files: [{
      path: "registry/eldoraui/logo-timeline.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/logo-timeline.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "logo-timeline"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "dock-text": {
    name: "dock-text",
    description: "A dock text component with interactive hover effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/dock-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/dock-text.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "dock-text"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "holographic-card": {
    name: "holographic-card",
    description: "An interactive card with a holographic gradient and mouse‑reactive tilt effect.",
    type: "registry:ui",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/eldoraui/holographic-card.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/holographic-card.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "holographic-card"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "safari-browser-demo": {
    name: "safari-browser-demo",
    description: "Example showing a safari-browser-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/safari-browser"],
    categories: [],
    files: [{
      path: "registry/example/safari-browser-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/safari-browser-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "safari-browser-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "macbook-pro-demo": {
    name: "macbook-pro-demo",
    description: "Example showing a macbook-pro-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/macbook-pro"],
    categories: [],
    files: [{
      path: "registry/example/macbook-pro-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/macbook-pro-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "macbook-pro-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "iphone-17-pro-demo": {
    name: "iphone-17-pro-demo",
    description: "Example showing a iphone-17-pro-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/iphone-17-pro"],
    categories: [],
    files: [{
      path: "registry/example/iphone-17-pro-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/iphone-17-pro-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "iphone-17-pro-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "ipad-demo": {
    name: "ipad-demo",
    description: "Example showing a ipad-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/ipad"],
    categories: [],
    files: [{
      path: "registry/example/ipad-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/ipad-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "ipad-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "browser-demo": {
    name: "browser-demo",
    description: "Example showing a browser-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/browser"],
    categories: [],
    files: [{
      path: "registry/example/browser-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/browser-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "browser-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "browser-demo-2": {
    name: "browser-demo-2",
    description: "Example showing a browser-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/browser"],
    categories: [],
    files: [{
      path: "registry/example/browser-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/browser-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "browser-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo": {
    name: "cobe-globe-demo",
    description: "Example showing a cobe-globe-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    categories: [],
    files: [{
      path: "registry/example/cobe-globe-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "cobe-globe-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo-2": {
    name: "cobe-globe-demo-2",
    description: "Example showing a cobe-globe-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    categories: [],
    files: [{
      path: "registry/example/cobe-globe-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "cobe-globe-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo-3": {
    name: "cobe-globe-demo-3",
    description: "Example showing a cobe-globe-demo-3 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    categories: [],
    files: [{
      path: "registry/example/cobe-globe-demo-3.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo-3.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "cobe-globe-demo-3"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo-4": {
    name: "cobe-globe-demo-4",
    description: "Example showing a cobe-globe-demo-4 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    categories: [],
    files: [{
      path: "registry/example/cobe-globe-demo-4.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo-4.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "cobe-globe-demo-4"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe-globe-demo-5": {
    name: "cobe-globe-demo-5",
    description: "Example showing a cobe-globe-demo-5 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/cobe-globe"],
    categories: [],
    files: [{
      path: "registry/example/cobe-globe-demo-5.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/cobe-globe-demo-5.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "cobe-globe-demo-5"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "github-inline-comments-demo": {
    name: "github-inline-comments-demo",
    description: "Example showing a github-inline-comments-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/github-inline-comments"],
    categories: [],
    files: [{
      path: "registry/example/github-inline-comments-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/github-inline-comments-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "github-inline-comments-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-badge-demo": {
    name: "animated-badge-demo",
    description: "Example showing a animated-badge-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/animated-badge"],
    categories: [],
    files: [{
      path: "registry/example/animated-badge-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/animated-badge-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-badge-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo": {
    name: "grid-demo",
    description: "Example showing a grid-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    categories: [],
    files: [{
      path: "registry/example/grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "grid-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo-2": {
    name: "grid-demo-2",
    description: "Example showing a grid-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    categories: [],
    files: [{
      path: "registry/example/grid-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "grid-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo-3": {
    name: "grid-demo-3",
    description: "Example showing a grid-demo-3 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    categories: [],
    files: [{
      path: "registry/example/grid-demo-3.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo-3.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "grid-demo-3"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo-4": {
    name: "grid-demo-4",
    description: "Example showing a grid-demo-4 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    categories: [],
    files: [{
      path: "registry/example/grid-demo-4.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo-4.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "grid-demo-4"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "grid-demo-5": {
    name: "grid-demo-5",
    description: "Example showing a grid-demo-5 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/grid"],
    categories: [],
    files: [{
      path: "registry/example/grid-demo-5.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/grid-demo-5.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "grid-demo-5"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "clerk-otp-demo": {
    name: "clerk-otp-demo",
    description: "Example showing a clerk-otp-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/clerk-otp"],
    categories: [],
    files: [{
      path: "registry/example/clerk-otp-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/clerk-otp-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "clerk-otp-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "clerk-otp-demo-2": {
    name: "clerk-otp-demo-2",
    description: "Example showing a clerk-otp-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/clerk-otp"],
    categories: [],
    files: [{
      path: "registry/example/clerk-otp-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/clerk-otp-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "clerk-otp-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "integrations-demo": {
    name: "integrations-demo",
    description: "Example showing a integrations-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/integrations"],
    categories: [],
    files: [{
      path: "registry/example/integrations-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/integrations-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "integrations-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "integrations-demo-2": {
    name: "integrations-demo-2",
    description: "Example showing a integrations-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/integrations"],
    categories: [],
    files: [{
      path: "registry/example/integrations-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/integrations-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "integrations-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "terminal-demo": {
    name: "terminal-demo",
    description: "Example showing a terminal-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/terminal"],
    categories: [],
    files: [{
      path: "registry/example/terminal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/terminal-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "terminal-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonal-slider-demo": {
    name: "testimonal-slider-demo",
    description: "Example showing a testimonal-slider-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/testimonal-slider"],
    categories: [],
    files: [{
      path: "registry/example/testimonal-slider-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/testimonal-slider-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "testimonal-slider-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "map-demo": {
    name: "map-demo",
    description: "Example showing a map component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/map"],
    categories: [],
    files: [{
      path: "registry/example/map-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/map-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "map-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "svg-ripple-effect-demo": {
    name: "svg-ripple-effect-demo",
    description: "Example showing a svg-ripple-effect component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/svg-ripple-effect"],
    categories: [],
    files: [{
      path: "registry/example/svg-ripple-effect-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/svg-ripple-effect-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "svg-ripple-effect-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "svg-ripple-effect-demo-2": {
    name: "svg-ripple-effect-demo-2",
    description: "Example showing a svg-ripple-effect-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/svg-ripple-effect"],
    categories: [],
    files: [{
      path: "registry/example/svg-ripple-effect-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/svg-ripple-effect-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "svg-ripple-effect-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-frameworks-demo": {
    name: "animated-frameworks-demo",
    description: "Example showing a animated-frameworks-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/animated-frameworks"],
    categories: [],
    files: [{
      path: "registry/example/animated-frameworks-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/animated-frameworks-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-frameworks-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "blur-in-text-demo": {
    name: "blur-in-text-demo",
    description: "Example showing a blur-in-text-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/blur-in-text"],
    categories: [],
    files: [{
      path: "registry/example/blur-in-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/blur-in-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "blur-in-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fade-text-demo": {
    name: "fade-text-demo",
    description: "Example showing a fade-text-demo component with all directions.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/fade-text"],
    categories: [],
    files: [{
      path: "registry/example/fade-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/fade-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "fade-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fade-text-demo-2": {
    name: "fade-text-demo-2",
    description: "Example showing a fade-text-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/fade-text"],
    categories: [],
    files: [{
      path: "registry/example/fade-text-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/fade-text-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "fade-text-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fade-text-demo-3": {
    name: "fade-text-demo-3",
    description: "Example showing a fade-text-demo-3 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/fade-text"],
    categories: [],
    files: [{
      path: "registry/example/fade-text-demo-3.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/fade-text-demo-3.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "fade-text-demo-3"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "gradual-spacing-text-demo": {
    name: "gradual-spacing-text-demo",
    description: "Example showing a gradual-spacing-text-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/gradual-spacing-text"],
    categories: [],
    files: [{
      path: "registry/example/gradual-spacing-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/gradual-spacing-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "gradual-spacing-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "letter-pull-up-text-demo": {
    name: "letter-pull-up-text-demo",
    description: "Example showing a letter-pull-up-text-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/letter-pull-up-text"],
    categories: [],
    files: [{
      path: "registry/example/letter-pull-up-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/letter-pull-up-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "letter-pull-up-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "multi-direction-slide-text-demo": {
    name: "multi-direction-slide-text-demo",
    description: "Example showing a multi-direction-slide-text-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/multi-direction-slide-text"],
    categories: [],
    files: [{
      path: "registry/example/multi-direction-slide-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/multi-direction-slide-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "multi-direction-slide-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "seperate-away-text-demo": {
    name: "seperate-away-text-demo",
    description: "Example showing a seperate-away-text-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/seperate-away-text"],
    categories: [],
    files: [{
      path: "registry/example/seperate-away-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/seperate-away-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "seperate-away-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "wavy-text-demo": {
    name: "wavy-text-demo",
    description: "Example showing a wavy-text-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/wavy-text"],
    categories: [],
    files: [{
      path: "registry/example/wavy-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/wavy-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "wavy-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "word-pull-up-text-demo": {
    name: "word-pull-up-text-demo",
    description: "Example showing a word-pull-up-text-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/word-pull-up-text"],
    categories: [],
    files: [{
      path: "registry/example/word-pull-up-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/word-pull-up-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "word-pull-up-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "novatrix-background-demo": {
    name: "novatrix-background-demo",
    description: "Example showing a novatrix-background-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/novatrix-background"],
    categories: [],
    files: [{
      path: "registry/example/novatrix-background-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/novatrix-background-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "novatrix-background-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "novatrix-background-demo-2": {
    name: "novatrix-background-demo-2",
    description: "Example showing a novatrix-background-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/novatrix-background"],
    categories: [],
    files: [{
      path: "registry/example/novatrix-background-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/novatrix-background-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "novatrix-background-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "photon-beam-demo": {
    name: "photon-beam-demo",
    description: "Example showing a photon-beam-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/photon-beam"],
    categories: [],
    files: [{
      path: "registry/example/photon-beam-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/photon-beam-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "photon-beam-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hacker-background-demo": {
    name: "hacker-background-demo",
    description: "Example showing a hacker-background-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/hacker-background"],
    categories: [],
    files: [{
      path: "registry/example/hacker-background-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/hacker-background-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "hacker-background-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hacker-background-demo-2": {
    name: "hacker-background-demo-2",
    description: "Example showing a hacker-background-demo-2 component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/hacker-background"],
    categories: [],
    files: [{
      path: "registry/example/hacker-background-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/hacker-background-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "hacker-background-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "card-flip-hover-demo": {
    name: "card-flip-hover-demo",
    description: "Example showing a card-flip-hover-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/card-flip-hover"],
    categories: [],
    files: [{
      path: "registry/example/card-flip-hover-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/card-flip-hover-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "card-flip-hover-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scale-letter-text-demo": {
    name: "scale-letter-text-demo",
    description: "Example showing a scale-letter-text-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/scale-letter-text"],
    categories: [],
    files: [{
      path: "registry/example/scale-letter-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/scale-letter-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "scale-letter-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "font-weight-text-demo": {
    name: "font-weight-text-demo",
    description: "Example showing a font-weight-text-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/font-weight-text"],
    categories: [],
    files: [{
      path: "registry/example/font-weight-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/font-weight-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "font-weight-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-grid-pattern-demo": {
    name: "animated-grid-pattern-demo",
    description: "Example showing a animated-grid-pattern-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/animated-grid-pattern"],
    categories: [],
    files: [{
      path: "registry/example/animated-grid-pattern-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/animated-grid-pattern-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-grid-pattern-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "live-button-demo": {
    name: "live-button-demo",
    description: "Example showing a live-button-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/live-button"],
    categories: [],
    files: [{
      path: "registry/example/live-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/live-button-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "live-button-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-shiny-button-demo": {
    name: "animated-shiny-button-demo",
    description: "Example showing a animated-shiny-button-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/animated-shiny-button"],
    categories: [],
    files: [{
      path: "registry/example/animated-shiny-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/animated-shiny-button-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-shiny-button-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animated-list-demo": {
    name: "animated-list-demo",
    description: "Example showing a animated-list-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/animated-list"],
    categories: [],
    files: [{
      path: "registry/example/animated-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/animated-list-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "animated-list-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "orbit-rotation-demo": {
    name: "orbit-rotation-demo",
    description: "Example showing a orbit-rotation-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/orbit-rotation"],
    categories: [],
    files: [{
      path: "registry/example/orbit-rotation-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/orbit-rotation-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "orbit-rotation-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logo-timeline-demo": {
    name: "logo-timeline-demo",
    description: "Example showing a logo-timeline-demo component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/logo-timeline"],
    categories: [],
    files: [{
      path: "registry/example/logo-timeline-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/logo-timeline-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "logo-timeline-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logo-timeline-demo-2": {
    name: "logo-timeline-demo-2",
    description: "Example showing a logo-timeline-demo-2 component with hover animation.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/logo-timeline"],
    categories: [],
    files: [{
      path: "registry/example/logo-timeline-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/logo-timeline-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "logo-timeline-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "dock-text-demo": {
    name: "dock-text-demo",
    description: "Example showing a dock-text component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/dock-text"],
    categories: [],
    files: [{
      path: "registry/example/dock-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/dock-text-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "dock-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "dock-text-demo-2": {
    name: "dock-text-demo-2",
    description: "Example showing a dock-text component with down prop.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/dock-text"],
    categories: [],
    files: [{
      path: "registry/example/dock-text-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/dock-text-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "dock-text-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "holographic-card-demo": {
    name: "holographic-card-demo",
    description: "Example showing a holographic-card component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/holographic-card"],
    categories: [],
    files: [{
      path: "registry/example/holographic-card-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/holographic-card-demo.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "holographic-card-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "holographic-card-demo-2": {
    name: "holographic-card-demo-2",
    description: "Example showing a holographic-card component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/holographic-card"],
    categories: [],
    files: [{
      path: "registry/example/holographic-card-demo-2.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/holographic-card-demo-2.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "holographic-card-demo-2"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "holographic-card-demo-3": {
    name: "holographic-card-demo-3",
    description: "Example showing a holographic-card component.",
    type: "registry:example",
    registryDependencies: ["@eldoraui/holographic-card"],
    categories: [],
    files: [{
      path: "registry/example/holographic-card-demo-3.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/holographic-card-demo-3.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "holographic-card-demo-3"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    categories: [],
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "utils"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "header-01": {
    name: "header-01",
    description: "A simple header.",
    type: "registry:block",
    registryDependencies: ["button","utils"],
    categories: ["header"],
    files: [{
      path: "registry/blocks/header-01/page.tsx",
      type: "registry:page",
      target: "app/header/page.tsx"
    },{
      path: "registry/blocks/header-01/components/navbar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/header-01/components/nav-menu.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/header-01/components/theme-toggle.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/header-01/lib/nav-links.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/header-01/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "header-01"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "header-02": {
    name: "header-02",
    description: "A simple header.",
    type: "registry:block",
    registryDependencies: ["button","utils"],
    categories: ["header"],
    files: [{
      path: "registry/blocks/header-02/page.tsx",
      type: "registry:page",
      target: "app/header-02/page.tsx"
    },{
      path: "registry/blocks/header-02/components/navbar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/header-02/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "header-02"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logo-cloud-01": {
    name: "logo-cloud-01",
    description: "A simple logo cloud.",
    type: "registry:block",
    registryDependencies: undefined,
    categories: ["logo-cloud"],
    files: [{
      path: "registry/blocks/logo-cloud-01/page.tsx",
      type: "registry:page",
      target: "app/logo-cloud/page.tsx"
    },{
      path: "registry/blocks/logo-cloud-01/components/logo-cloud.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/logo-cloud-01/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "logo-cloud-01"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logo-cloud-02": {
    name: "logo-cloud-02",
    description: "A logo cloud with flex wrap layout.",
    type: "registry:block",
    registryDependencies: undefined,
    categories: ["logo-cloud"],
    files: [{
      path: "registry/blocks/logo-cloud-02/page.tsx",
      type: "registry:page",
      target: "app/logo-cloud/page.tsx"
    },{
      path: "registry/blocks/logo-cloud-02/components/logo-cloud-02.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/logo-cloud-02/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "logo-cloud-02"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logo-cloud-03": {
    name: "logo-cloud-03",
    description: "A logo cloud with marquee effect.",
    type: "registry:block",
    registryDependencies: ["marquee"],
    categories: ["logo-cloud"],
    files: [{
      path: "registry/blocks/logo-cloud-03/page.tsx",
      type: "registry:page",
      target: "app/logo-cloud/page.tsx"
    },{
      path: "registry/blocks/logo-cloud-03/components/marquee.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/logo-cloud-03/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "logo-cloud-03"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logo-cloud-04": {
    name: "logo-cloud-04",
    description: "A logo cloud with motion.",
    type: "registry:block",
    registryDependencies: undefined,
    categories: ["logo-cloud"],
    files: [{
      path: "registry/blocks/logo-cloud-04/page.tsx",
      type: "registry:page",
      target: "app/logo-cloud/page.tsx"
    },{
      path: "registry/blocks/logo-cloud-04/components/logo-cloud-04.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/logo-cloud-04/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "logo-cloud-04"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonal-01": {
    name: "testimonal-01",
    description: "A testimonial slider.",
    type: "registry:block",
    registryDependencies: undefined,
    categories: ["testimonials"],
    files: [{
      path: "registry/blocks/testimonal-01/page.tsx",
      type: "registry:page",
      target: "app/testimonial/page.tsx"
    },{
      path: "registry/blocks/testimonal-01/components/carousel.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/testimonal-01/components/section.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/testimonal-01/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "testimonal-01"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonal-02": {
    name: "testimonal-02",
    description: "A testimonial marquee.",
    type: "registry:block",
    registryDependencies: ["utils"],
    categories: ["testimonials"],
    files: [{
      path: "registry/blocks/testimonal-02/page.tsx",
      type: "registry:page",
      target: "app/testimonial/page.tsx"
    },{
      path: "registry/blocks/testimonal-02/components/marquee.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/testimonal-02/components/testimonals.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/testimonal-02/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "testimonal-02"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonal-03": {
    name: "testimonal-03",
    description: "A testimonial card grid.",
    type: "registry:block",
    registryDependencies: [],
    categories: ["testimonials"],
    files: [{
      path: "registry/blocks/testimonal-03/page.tsx",
      type: "registry:page",
      target: "app/testimonial/page.tsx"
    },{
      path: "registry/blocks/testimonal-03/components/testimonal-03.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/testimonal-03/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "testimonal-03"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "features-01": {
    name: "features-01",
    description: "Features section with accordion and image carousel.",
    type: "registry:block",
    registryDependencies: undefined,
    categories: ["features"],
    files: [{
      path: "registry/blocks/features-01/page.tsx",
      type: "registry:page",
      target: "app/features/page.tsx"
    },{
      path: "registry/blocks/features-01/components/features.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/features-01/components/section.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/features-01/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "features-01"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cta-01": {
    name: "cta-01",
    description: "CTA with heading, grid background, and animated side lines.",
    type: "registry:block",
    registryDependencies: ["utils"],
    categories: ["cta"],
    files: [{
      path: "registry/blocks/cta-01/page.tsx",
      type: "registry:page",
      target: "app/cta/page.tsx"
    },{
      path: "registry/blocks/cta-01/components/cta.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/cta-01/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "cta-01"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cta-02": {
    name: "cta-02",
    description: "CTA with heading, button, and orbiting app icons.",
    type: "registry:block",
    registryDependencies: ["button","grid","utils"],
    categories: ["cta"],
    files: [{
      path: "registry/blocks/cta-02/page.tsx",
      type: "registry:page",
      target: "app/cta/page.tsx"
    },{
      path: "registry/blocks/cta-02/components/cta-02.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/cta-02/components/orbiting-circle.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/cta-02/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "cta-02"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cta-03": {
    name: "cta-03",
    description: "CTA with heading, button, and ripple background.",
    type: "registry:block",
    registryDependencies: ["utils"],
    categories: ["cta"],
    files: [{
      path: "registry/blocks/cta-03/page.tsx",
      type: "registry:page",
      target: "app/cta/page.tsx"
    },{
      path: "registry/blocks/cta-03/components/cta-03.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/cta-03/components/ripple-bg.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/cta-03/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "cta-03"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "pricing-01": {
    name: "pricing-01",
    description: "A pricing section.",
    type: "registry:block",
    registryDependencies: ["utils"],
    categories: ["pricing"],
    files: [{
      path: "registry/blocks/pricing-01/page.tsx",
      type: "registry:page",
      target: "app/pricing/page.tsx"
    },{
      path: "registry/blocks/pricing-01/components/pricing.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/pricing-01/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "pricing-01"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "pricing-02": {
    name: "pricing-02",
    description: "A pricing table with a dropdown menu.",
    type: "registry:block",
    registryDependencies: ["utils"],
    categories: ["pricing"],
    files: [{
      path: "registry/blocks/pricing-02/page.tsx",
      type: "registry:page",
      target: "app/pricing/page.tsx"
    },{
      path: "registry/blocks/pricing-02/components/pricing-table.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/pricing-02/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "pricing-02"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "footer-01": {
    name: "footer-01",
    description: "A footer.",
    type: "registry:block",
    registryDependencies: undefined,
    categories: ["footer"],
    files: [{
      path: "registry/blocks/footer-01/page.tsx",
      type: "registry:page",
      target: "app/footer/page.tsx"
    },{
      path: "registry/blocks/footer-01/components/footer.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/footer-01/components/theme-toggler.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/blocks/footer-01/page.tsx")
      const exportName = Object.keys(mod).find((key) => {
        const value = mod[key]
        return typeof value === "function" || typeof value === "object"
      }) || "footer-01"
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
}