// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {
  nav: [
    {
      title: "Getting Started",
      slug: "docs",
      items: [
        { title: "Introduction", href: "/docs/introduction" },
        { title: "Installation", href: "/docs/installation" },
       
      ]
    },
    {
      title: "Components",
      slug: "components",
      items: [
        {
          title: "Overview",
          href: "/components"
        },
       
       
        {
            title: "Special Animations",
            items: [
              
              { title: "Tag", href: "/components/special-animations/tag" },
              { title: "Cobe globe", href: "/components/special-animations/cobeglobe" },
              { title: "spotlight card", href: "/components/special-animations/spotlightcard"},
              { title: "Search", href: "/components/special-animations/searchmodal" },

              
            ]
          },

        {
          title: "Sections",
          items:[
            {title:"Bentogrid", href:"/components/sections/bentogrid"},
            { title:"companies", href:"/components/sections/companies"},
            {title:"Particles", href:"/components/sections/particles"},
            { title:"Pricing", href:"/components/sections/pricing"},
            {title:"Progress slider", href:"/components/sections/progressslider"},
            { title:"Timeline", href:"/components/sections/timeline"}


          ]
        },
       
        {
          title: "Forms",
          items: [
            { title: "Multi step form", href: "/components/forms/multistepform" },
            
          ]
        },
        {
          title: "Input",
          items: [
            { title: "calendar", href: "/components/input/calendar" },
            
          ]
        },
       
      ]
    },
    // {
    //     title: "Templates",
    //     slug: "docs",
    //     items: [
    //       { title: "Introduction", href: "/docs/introduction" },
    //       { title: "Installation", href: "/docs/installation" },
         
    //     ]
    //   },
  ]
};
