/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  "dynamicsquare": {
    name: "dynamicsquare",
    description: "A layout used to showcase the features of a product in a simple and elegant way.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/dynamicsquare.tsx",
      type: "registry:ui",
      target: "components/eldoraui/dynamicsquare.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/dynamicsquare.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "features": {
    name: "features",
    description: "A layout used to showcase the features of a product in a simple and elegant way.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/features.tsx",
      type: "registry:ui",
      target: "components/eldoraui/features.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/features.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "carousel": {
    name: "carousel",
    description: "A testimonal carousel.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/carousel.tsx",
      type: "registry:ui",
      target: "components/eldoraui/carousel.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/carousel.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hackerbg": {
    name: "hackerbg",
    description: "An Hacker like background.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/hackerbg.tsx",
      type: "registry:ui",
      target: "components/eldoraui/hackerbg.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/hackerbg.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "morphingtext": {
    name: "morphingtext",
    description: "A dynamic text morphing component for Eldora UI.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/morphingtext.tsx",
      type: "registry:ui",
      target: "components/eldoraui/morphingtext.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/morphingtext.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scrollprogress": {
    name: "scrollprogress",
    description: "Animated Scroll Progress for your pages",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/scrollprogress.tsx",
      type: "registry:ui",
      target: "components/eldoraui/scrollprogress.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/scrollprogress.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scrollbasedvelocity": {
    name: "scrollbasedvelocity",
    description: "Text animation that changes speed based on scroll position.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/scrollbasedvelocity.tsx",
      type: "registry:ui",
      target: "components/eldoraui/scrollbasedvelocity.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/scrollbasedvelocity.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "plusgrid": {
    name: "plusgrid",
    description: "A interactive component that enables zooming into images, videos and other elements.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/plusgrid.tsx",
      type: "registry:ui",
      target: "components/eldoraui/plusgrid.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/plusgrid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "link": {
    name: "link",
    description: "A component that displays a pointer when hovering over an element",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/link.tsx",
      type: "registry:ui",
      target: "components/eldoraui/link.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/link.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "featurefour": {
    name: "featurefour",
    description: "A layout used to showcase the features of a product in a simple and elegant way.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/featurefour.tsx",
      type: "registry:ui",
      target: "components/eldoraui/featurefour.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/featurefour.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animatedcard": {
    name: "animatedcard",
    description: "A layout used to showcase the features of a product in a simple and elegant way.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/animatedcard.tsx",
      type: "registry:ui",
      target: "components/eldoraui/animatedcard.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/animatedcard.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "sphereanimation": {
    name: "sphereanimation",
    description: "SVG sphere animation using animejs.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/sphere-animation.tsx",
      type: "registry:ui",
      target: "components/eldoraui/sphere-animation.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/sphere-animation.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "tweetgrid": {
    name: "tweetgrid",
    description: "A card that displays a tweet with the author's name, handle, and profile picture.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/tweetgrid.tsx",
      type: "registry:ui",
      target: "components/eldoraui/tweetgrid.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/tweetgrid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "signature": {
    name: "signature",
    description: "Component through which we can have digital signatures.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/signature.tsx",
      type: "registry:ui",
      target: "components/eldoraui/signature.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/signature.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "codesnippet": {
    name: "codesnippet",
    description: "A codesnippet from which we can copy commands.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/codesnippet.tsx",
      type: "registry:ui",
      target: "components/eldoraui/codesnippet.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/codesnippet.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "novatrix": {
    name: "novatrix",
    description: "A 3d shader background using vertex and fragment shader.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/novatrix.tsx",
      type: "registry:ui",
      target: "components/eldoraui/novatrix.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/novatrix.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fadedown": {
    name: "fadedown",
    description: "Text animation where the text fades down into view.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/fadedown.tsx",
      type: "registry:ui",
      target: "components/eldoraui/fadedown.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/fadedown.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fadein": {
    name: "fadein",
    description: "Text animation that smoothly fades text into visibility.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/fadein.tsx",
      type: "registry:ui",
      target: "components/eldoraui/fadein.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/fadein.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "marquee": {
    name: "marquee",
    description: "An infinite scrolling component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/marquee.tsx",
      type: "registry:ui",
      target: "components/eldoraui/marquee.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/marquee.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fadeup": {
    name: "fadeup",
    description: "Text animation where the text fades down into view.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/fadeup.tsx",
      type: "registry:ui",
      target: "components/eldoraui/fadeup.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/fadeup.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "blurin": {
    name: "blurin",
    description: "An animated text component that blurs in the text.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/blurin.tsx",
      type: "registry:ui",
      target: "components/eldoraui/blurin.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/blurin.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "gradualspacing": {
    name: "gradualspacing",
    description: "Text animation that increases letter spacing gradually.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/gradualspacing.tsx",
      type: "registry:ui",
      target: "components/eldoraui/gradualspacing.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/gradualspacing.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "letterpullup": {
    name: "letterpullup",
    description: "Text animation where each letter pulls up into place.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/letterpullup.tsx",
      type: "registry:ui",
      target: "components/eldoraui/letterpullup.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/letterpullup.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scrollprogress": {
    name: "scrollprogress",
    description: "Particles are a fun way to add some visual flair to your website. They can be used to create a sense of depth, movement, and interactivity.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/scrollprogress.tsx",
      type: "registry:ui",
      target: "components/eldoraui/scrollprogress.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/scrollprogress.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scaleslider": {
    name: "scaleslider",
    description: "An animated scale slider component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/scaleslider.tsx",
      type: "registry:ui",
      target: "components/eldoraui/scaleslider.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/scaleslider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "multidirectionslide": {
    name: "multidirectionslide",
    description: "Text animation where text slides in from multiple directions.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/multidirectionslide.tsx",
      type: "registry:ui",
      target: "components/eldoraui/multidirectionslide.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/multidirectionslide.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "seperateaway": {
    name: "seperateaway",
    description: "Text animation where letters move apart from each other.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/seperateaway.tsx",
      type: "registry:ui",
      target: "components/eldoraui/seperateaway.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/seperateaway.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "wavytext": {
    name: "wavytext",
    description: "Text animation where the text moves in a wavy motion.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/wavytext.tsx",
      type: "registry:ui",
      target: "components/eldoraui/wavytext.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/wavytext.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "wordpullup": {
    name: "wordpullup",
    description: "Text animation where entire words pull up into view.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/wordpullup.tsx",
      type: "registry:ui",
      target: "components/eldoraui/wordpullup.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/wordpullup.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "interactivebutton": {
    name: "interactivebutton",
    description: "A visually engaging button component that responds to hover with dynamic transitions, adapting smoothly between light and dark modes for enhanced user interactivity.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/interactivebutton.tsx",
      type: "registry:ui",
      target: "components/eldoraui/interactivebutton.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/interactivebutton.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "integrations": {
    name: "integrations",
    description: "programmatically generated icons using marquee and fade effects.",
    type: "registry:ui",
    registryDependencies: ["marquee"],
    files: [{
      path: "registry/eldoraui/integrations.tsx",
      type: "registry:ui",
      target: "components/eldoraui/integrations.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/integrations.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "staticstepper": {
    name: "staticstepper",
    description: "A Simple way to show the steps for users.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/staticstepper.tsx",
      type: "registry:ui",
      target: "components/eldoraui/staticstepper.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/staticstepper.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "bentogrid": {
    name: "bentogrid",
    description: "A modern grid layout designed for visually appealing and organized feature showcases.",
    type: "registry:ui",
    registryDependencies: ["keyboard","logocluster","map"],
    files: [{
      path: "registry/eldoraui/bentocard.tsx",
      type: "registry:ui",
      target: "components/eldoraui/bentocard.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/bentocard.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cardcomment": {
    name: "cardcomment",
    description: "Animated card layout for messages",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/animatedcardcomment.tsx",
      type: "registry:ui",
      target: "components/eldoraui/animatedcardcomment.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/animatedcardcomment.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hoverme": {
    name: "hoverme",
    description: "An animated hover button.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/hoverme.tsx",
      type: "registry:ui",
      target: "components/eldoraui/hoverme.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/hoverme.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "gitstarbutton": {
    name: "gitstarbutton",
    description: "An animated button to showcase Github stars.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/gitstarbutton.tsx",
      type: "registry:ui",
      target: "components/eldoraui/gitstarbutton.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/gitstarbutton.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "shimmerbutton": {
    name: "shimmerbutton",
    description: "A shimmer button component with dynamic styles.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/shimmerbutton.tsx",
      type: "registry:ui",
      target: "components/eldoraui/shimmerbutton.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/shimmerbutton.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "spotlightbutton": {
    name: "spotlightbutton",
    description: "Button which Highlights while hovering by a spotlight.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/spotlightbutton.tsx",
      type: "registry:ui",
      target: "components/eldoraui/spotlightbutton.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/spotlightbutton.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animatedborderbutton": {
    name: "animatedborderbutton",
    description: "A button with a shimmering light which travels around the perimeter.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/animatedborderbutton.tsx",
      type: "registry:ui",
      target: "components/eldoraui/animatedborderbutton.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/animatedborderbutton.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "header": {
    name: "header",
    description: "These components are used to build the header of the website",
    type: "registry:ui",
    registryDependencies: ["link","plusgrid"],
    files: [{
      path: "registry/eldoraui/header.tsx",
      type: "registry:ui",
      target: "components/eldoraui/header.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/header.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonalslider": {
    name: "testimonalslider",
    description: "Testimonals slider",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/testimonalslider.tsx",
      type: "registry:ui",
      target: "components/eldoraui/testimonalslider.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/testimonalslider.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobe": {
    name: "cobe",
    description: "A globe animation which is Interactive and customizable.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/cobe.tsx",
      type: "registry:ui",
      target: "components/eldoraui/cobe.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/cobe.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonals": {
    name: "testimonals",
    description: "Testimonal marquee",
    type: "registry:ui",
    registryDependencies: ["marquee"],
    files: [{
      path: "registry/eldoraui/testimonals.tsx",
      type: "registry:ui",
      target: "components/eldoraui/testimonals.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/testimonals.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "warpcontainer": {
    name: "warpcontainer",
    description: "A container component that applies a warp animation effect to its children.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/wrapanimationcontainer.tsx",
      type: "registry:ui",
      target: "components/eldoraui/wrapanimationcontainer.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/wrapanimationcontainer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scratchtoreveal": {
    name: "scratchtoreveal",
    description: "The ScratchToReveal component creates an interactive scratch-off effect with customizable dimensions and animations, revealing hidden content beneath.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/scratchtoreveal.tsx",
      type: "registry:ui",
      target: "components/eldoraui/scratchtoreveal.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/scratchtoreveal.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "keyboard": {
    name: "keyboard",
    description: "A shiny button component with dynamic styles in the dark mode or light mode.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/keyboard.tsx",
      type: "registry:ui",
      target: "components/eldoraui/keyboard.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/keyboard.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logocluster": {
    name: "logocluster",
    description: "Sliding box animation that reveals text behind it.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/logocluster.tsx",
      type: "registry:ui",
      target: "components/eldoraui/logocluster.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/logocluster.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "map": {
    name: "map",
    description: "Shine border is an animated background border effect.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/eldoraui/map.tsx",
      type: "registry:ui",
      target: "components/eldoraui/map.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/eldoraui/map.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fadedowndemo": {
    name: "fadedowndemo",
    description: "Example showing a spotlight effect that follows your mouse cursor and highlights borders on hover.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/fadedown"],
    files: [{
      path: "registry/demos/fadedown-demo.tsx",
      type: "registry:example",
      target: "components/fadedown-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/fadedown-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "dynamicsquaredemo": {
    name: "dynamicsquaredemo",
    description: "Example showing a mockup of an Android device.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/dynamicsquare"],
    files: [{
      path: "registry/demos/dynamicsquare-demo.tsx",
      type: "registry:example",
      target: "components/dynamicsquare-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/dynamicsquare-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonalcarouseldemo": {
    name: "testimonalcarouseldemo",
    description: "Second example showing a mockup of an Android device.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/carousel"],
    files: [{
      path: "registry/demos/testimonal-carousel.tsx",
      type: "registry:example",
      target: "components/carousel-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/testimonal-carousel.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hackerbgdemo": {
    name: "hackerbgdemo",
    description: "Third example showing a mockup of an Android device.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/hackerbg"],
    files: [{
      path: "registry/demos/hackerbg-demo.tsx",
      type: "registry:example",
      target: "components/hackerbg-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/hackerbg-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "sphereanimationdemo": {
    name: "sphereanimationdemo",
    description: "Example showing a card with a time warping background effect.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/sphereanimation"],
    files: [{
      path: "registry/demos/sphere-animation-demo.tsx",
      type: "registry:example",
      target: "components/sphere-animation-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/sphere-animation-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "featuresdemo": {
    name: "featuresdemo",
    description: "Example showing a text component with a moving line shadow.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/features"],
    files: [{
      path: "registry/demos/features-demo.tsx",
      type: "registry:example",
      target: "components/features-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/features-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "integrationsdemo": {
    name: "integrationsdemo",
    description: "Example showing a beautiful aurora text effect.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/integrations"],
    files: [{
      path: "registry/demos/integrations-demo.tsx",
      type: "registry:example",
      target: "components/integrations-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/integrations-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logomarqueedemo": {
    name: "logomarqueedemo",
    description: "Example showing a dynamic text morphing component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/marquee"],
    files: [{
      path: "registry/demos/logomarquee.tsx",
      type: "registry:example",
      target: "components/logomarquee.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/logomarquee.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "codesnippetdemo": {
    name: "codesnippetdemo",
    description: "Example showing animated scroll progress for your pages.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/codesnippet"],
    files: [{
      path: "registry/demos/codesnippet-demo.tsx",
      type: "registry:example",
      target: "components/codesnippet-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/codesnippet-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "staticstepperdemo": {
    name: "staticstepperdemo",
    description: "Example showing a lens effect component",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/staticstepper"],
    files: [{
      path: "registry/demos/staticstepper-demo.tsx",
      type: "registry:example",
      target: "components/staticstepper-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/staticstepper-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "featurefourdemo": {
    name: "featurefourdemo",
    description: "Second example showing a lens effect component",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/featurefour"],
    files: [{
      path: "registry/demos/featurefour-demo.tsx",
      type: "registry:example",
      target: "components/featurefour-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/featurefour-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "animatedcarddemo": {
    name: "animatedcarddemo",
    description: "Third example showing a lens effect component",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/animatedcard"],
    files: [{
      path: "registry/demos/animatedcard-demo.tsx",
      type: "registry:example",
      target: "components/animatedcard-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/animatedcard-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "signaturedemo": {
    name: "signaturedemo",
    description: "Example showing a pointer effect component",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/signature"],
    files: [{
      path: "registry/demos/signature-demo.tsx",
      type: "registry:example",
      target: "components/signature-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/signature-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "gradientpricingdemo": {
    name: "gradientpricingdemo",
    description: "Example showing a beautiful neon card effect.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/gradientpricing-demo.tsx",
      type: "registry:example",
      target: "components/gradientpricing-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/gradientpricing-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scrollprogressdemo": {
    name: "scrollprogressdemo",
    description: "Example showing a meteor shower effect.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/scrollprogress"],
    files: [{
      path: "registry/demos/scrollprogress-demo.tsx",
      type: "registry:example",
      target: "components/scrollprogress-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/scrollprogress-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cardcommentdemo": {
    name: "cardcommentdemo",
    description: "Example showing a background grid pattern made with SVGs.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/cardcomment"],
    files: [{
      path: "registry/demos/cardcomment-demo.tsx",
      type: "registry:example",
      target: "components/cardcomment-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/cardcomment-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scalesliderdemo": {
    name: "scalesliderdemo",
    description: "Example showing a grid pattern with linear gradient effects.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/scaleslider"],
    files: [{
      path: "registry/demos/scaleslider-demo.tsx",
      type: "registry:example",
      target: "components/scaleslider-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/scaleslider-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scratchtorevealdemo": {
    name: "scratchtorevealdemo",
    description: "Example showing a dashed grid pattern.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/scratchtoreveal"],
    files: [{
      path: "registry/demos/scratchtoreveal-demo.tsx",
      type: "registry:example",
      target: "components/scratchtoreveal-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/scratchtoreveal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "wrapcontainerdemo": {
    name: "wrapcontainerdemo",
    description: "Example showing a background dot pattern made with SVGs.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/wrapcontainer"],
    files: [{
      path: "registry/demos/wrapanimation-demo.tsx",
      type: "registry:example",
      target: "components/wrapanimation-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/wrapanimation-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "tweetgriddemo": {
    name: "tweetgriddemo",
    description: "Example showing a dot pattern with linear gradient effects.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/tweetgrid"],
    files: [{
      path: "registry/demos/tweetgrid-demo.tsx",
      type: "registry:example",
      target: "components/tweetgrid-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/tweetgrid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fadeindemo": {
    name: "fadeindemo",
    description: "Example showing a fadeindemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/fadein"],
    files: [{
      path: "registry/demos/fadein-demo.tsx",
      type: "registry:example",
      target: "components/fadein-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/fadein-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "fadeupdemo": {
    name: "fadeupdemo",
    description: "Example showing a fadeupdemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/fadeup"],
    files: [{
      path: "registry/demos/fadeup-demo.tsx",
      type: "registry:example",
      target: "components/fadeup-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/fadeup-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "gradualspacingdemo": {
    name: "gradualspacingdemo",
    description: "Example showing a gradualspacingdemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/gradualspacing"],
    files: [{
      path: "registry/demos/gradualspacing-demo.tsx",
      type: "registry:example",
      target: "components/gradualspacing-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/gradualspacing-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "letterpullupdemo": {
    name: "letterpullupdemo",
    description: "Example showing a letterpullupdemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/letterpullup"],
    files: [{
      path: "registry/demos/letterpullup-demo.tsx",
      type: "registry:example",
      target: "components/letterpullup-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/letterpullup-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "multidirectionalslidedemo": {
    name: "multidirectionalslidedemo",
    description: "Example showing a multidirectionalslidedemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/multidirectionalslide"],
    files: [{
      path: "registry/demos/multidirectionalslide-demo.tsx",
      type: "registry:example",
      target: "components/multidirectionalslide-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/multidirectionalslide-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "scrollbasedvelocitydemo": {
    name: "scrollbasedvelocitydemo",
    description: "Example showing a scrollbasedvelocitydemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/scrollbasedvelocity"],
    files: [{
      path: "registry/demos/scrollbasedvelocity-demo.tsx",
      type: "registry:example",
      target: "components/scrollbasedvelocity-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/scrollbasedvelocity-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "seperateawaydemo": {
    name: "seperateawaydemo",
    description: "Example showing a seperateawaydemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/seperateaway"],
    files: [{
      path: "registry/demos/seperateaway-demo.tsx",
      type: "registry:example",
      target: "components/seperateaway-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/seperateaway-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "wavytextdemo": {
    name: "wavytextdemo",
    description: "Example showing a wavytextdemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/wavytext"],
    files: [{
      path: "registry/demos/wavytext-demo.tsx",
      type: "registry:example",
      target: "components/wavytext-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/wavytext-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "morphingtextdemo": {
    name: "morphingtextdemo",
    description: "Example showing a morphingtextdemo component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/morphingtext-demo.tsx",
      type: "registry:example",
      target: "components/morphingtext-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/morphingtext-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "blurindemo": {
    name: "blurindemo",
    description: "Example showing a blurindemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/blurin"],
    files: [{
      path: "registry/demos/blurin-demo.tsx",
      type: "registry:example",
      target: "components/blurin-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/blurin-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "wordpullupdemo": {
    name: "wordpullupdemo",
    description: "Example showing a wordpullupdemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/wordpullup"],
    files: [{
      path: "registry/demos/wordpullup-demo.tsx",
      type: "registry:example",
      target: "components/wordpullup-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/wordpullup-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "bentodemo": {
    name: "bentodemo",
    description: "Example showing a bentodemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/bentocard"],
    files: [{
      path: "registry/demos/bento-demo.tsx",
      type: "registry:example",
      target: "components/bento-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/bento-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "headerdemo": {
    name: "headerdemo",
    description: "Example showing a headerdemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/header"],
    files: [{
      path: "registry/demos/header-demo.tsx",
      type: "registry:example",
      target: "components/header-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/header-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "novatrixdemo": {
    name: "novatrixdemo",
    description: "Example showing a novatrixdemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/novatrix"],
    files: [{
      path: "registry/demos/novatrixbg-demo.tsx",
      type: "registry:example",
      target: "components/novatrixbg-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/novatrixbg-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonalsliderdemo": {
    name: "testimonalsliderdemo",
    description: "Example showing a testimonalsliderdemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/testimonalslider"],
    files: [{
      path: "registry/demos/testimonalslider-demo.tsx",
      type: "registry:example",
      target: "components/testimonalslider-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/testimonalslider-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "cobeglobedemo": {
    name: "cobeglobedemo",
    description: "Example showing a cobeglobedemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/cobe"],
    files: [{
      path: "registry/demos/cobeglobe-demo.tsx",
      type: "registry:example",
      target: "components/cobeglobe-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/cobeglobe-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "testimonalsdemo": {
    name: "testimonalsdemo",
    description: "Example showing a testimonalsdemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/testimonals"],
    files: [{
      path: "registry/demos/testimonals-demo.tsx",
      type: "registry:example",
      target: "components/testimonals-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/testimonals-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "hovermedemo": {
    name: "hovermedemo",
    description: "Example showing a hovermedemo component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/hoverme-demo.tsx",
      type: "registry:example",
      target: "components/hoverme-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/hoverme-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "gitstardemo": {
    name: "gitstardemo",
    description: "Example showing a gitstardemo component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/gitstar-demo.tsx",
      type: "registry:example",
      target: "components/gitstar-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/gitstar-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "logoclouddemo": {
    name: "logoclouddemo",
    description: "Example showing a logoclouddemo component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/logocloud-demo.tsx",
      type: "registry:example",
      target: "components/logocloud-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/logocloud-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "interactivebuttondemo": {
    name: "interactivebuttondemo",
    description: "Example showing a interactivebuttondemo component.",
    type: "registry:example",
    registryDependencies: ["https://eldoraui.site/r/interactivebutton"],
    files: [{
      path: "registry/demos/interactivebutton-demo.tsx",
      type: "registry:example",
      target: "components/interactivebutton-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/interactivebutton-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "pricingdemo": {
    name: "pricingdemo",
    description: "Example showing a pricingdemo component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/pricing-demo.tsx",
      type: "registry:example",
      target: "components/pricing-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/pricing-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "shimmerdemo": {
    name: "shimmerdemo",
    description: "Example showing a shimmerdemo component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/shimmerbutton-demo.tsx",
      type: "registry:example",
      target: "components/shimmerbutton-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/shimmerbutton-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "colorchangingdemo": {
    name: "colorchangingdemo",
    description: "Example showing a colorchangingdemo component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/colorchanging-demo.tsx",
      type: "registry:example",
      target: "components/colorchanging-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/colorchanging-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "spotlightdemo": {
    name: "spotlightdemo",
    description: "Example showing a spotlightdemo component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/spotlight-demo.tsx",
      type: "registry:example",
      target: "components/spotlight-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/spotlight-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "borderdemo": {
    name: "borderdemo",
    description: "Example showing a borderdemo component.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/demos/borderbutton-demo.tsx",
      type: "registry:example",
      target: "components/borderbutton-demo.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/demos/borderbutton-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    meta: undefined,
  },
  }